language: rust
rust:
- stable
jobs:
  include:
  - stage: "Build on Linux"
    os: linux
    deploy:
      provider: releases
      api_key:
        secure: Ed5OZTQ9c57rnJO8Lz5s8AIMICo4bMhvwLNkpyQB1fjtPKJBwqa83OwLjppg+maOzsUAjaWI0D0SzdH0K8w8YGU5PK8vzFyIuU2RoFm54u6aj9Q0xM4/FU7rCTPZcpFtutpCnaflP6gzIvT9NhAtAP9n+GD23VFIpOS4KdO7Fq023sTtNHlotDon2o5GswKZg2Xry3KYSr/fhKi7y/0LS20YrFjAJdQq7Vbtipp/b6cQ0iWFHUjRzFD5bF5Dcv9z6JhGxhtx7E3tX+0IP/fhvqFYHLNR7h0Peai8kMwE0bcdsWHP7/RT6eElxnwxfp9xUrCTfBud+D6X3MBe0D3G4ww+9vPQeLyTHbFtrW/QHtWHO05SgBj/Hr9s7DK/1sAeQSGz9KAAtD58W6NZXctD1QOcS9BaskXmzgMYPwGiRy+ClmG+aoIlYjKfSeiPShpM7w4N1tmD6cS7PHIq9MpuVv9vNQZP8DGHy02C5/eQPMA3qz5hBUQDdQtJ7x/muH5JMZ/Q1drg69xBpsjrM8Gw0fdbUrYcqq0bjoZF0J93QXoSZWn/1BmDJihrIp7DXaJXuLa3vs5ZnVgbkIf73jptiSLQeofCijGZEwjSOJ0hZ4hwH8P4DGTURNI4GbWqMvWjmYJ3XAC5lBWg/r4cVmvMYlx13SxMrLHMRg24ncWVAkY=
      draft: true
      file_glob: true
      file: build/jni-libs/libwasmtime_jni_*
      cleanup: true
      on:
        tags: true
        repo: kawamuray/wasmtime-java
  - stage: "Build on Mac"
    os: osx
    deploy:
      provider: releases
      api_key:
        secure: Ed5OZTQ9c57rnJO8Lz5s8AIMICo4bMhvwLNkpyQB1fjtPKJBwqa83OwLjppg+maOzsUAjaWI0D0SzdH0K8w8YGU5PK8vzFyIuU2RoFm54u6aj9Q0xM4/FU7rCTPZcpFtutpCnaflP6gzIvT9NhAtAP9n+GD23VFIpOS4KdO7Fq023sTtNHlotDon2o5GswKZg2Xry3KYSr/fhKi7y/0LS20YrFjAJdQq7Vbtipp/b6cQ0iWFHUjRzFD5bF5Dcv9z6JhGxhtx7E3tX+0IP/fhvqFYHLNR7h0Peai8kMwE0bcdsWHP7/RT6eElxnwxfp9xUrCTfBud+D6X3MBe0D3G4ww+9vPQeLyTHbFtrW/QHtWHO05SgBj/Hr9s7DK/1sAeQSGz9KAAtD58W6NZXctD1QOcS9BaskXmzgMYPwGiRy+ClmG+aoIlYjKfSeiPShpM7w4N1tmD6cS7PHIq9MpuVv9vNQZP8DGHy02C5/eQPMA3qz5hBUQDdQtJ7x/muH5JMZ/Q1drg69xBpsjrM8Gw0fdbUrYcqq0bjoZF0J93QXoSZWn/1BmDJihrIp7DXaJXuLa3vs5ZnVgbkIf73jptiSLQeofCijGZEwjSOJ0hZ4hwH8P4DGTURNI4GbWqMvWjmYJ3XAC5lBWg/r4cVmvMYlx13SxMrLHMRg24ncWVAkY=
      draft: true
      file_glob: true
      file: build/jni-libs/libwasmtime_jni_*
      cleanup: true
      on:
        tags: true
        repo: kawamuray/wasmtime-java
  - stage: "Build and publish universal jar"
    os: linux
    before_deploy: .travis/build-universal-jar.sh
    deploy:
      provider: releases
      api_key:
        secure: Ed5OZTQ9c57rnJO8Lz5s8AIMICo4bMhvwLNkpyQB1fjtPKJBwqa83OwLjppg+maOzsUAjaWI0D0SzdH0K8w8YGU5PK8vzFyIuU2RoFm54u6aj9Q0xM4/FU7rCTPZcpFtutpCnaflP6gzIvT9NhAtAP9n+GD23VFIpOS4KdO7Fq023sTtNHlotDon2o5GswKZg2Xry3KYSr/fhKi7y/0LS20YrFjAJdQq7Vbtipp/b6cQ0iWFHUjRzFD5bF5Dcv9z6JhGxhtx7E3tX+0IP/fhvqFYHLNR7h0Peai8kMwE0bcdsWHP7/RT6eElxnwxfp9xUrCTfBud+D6X3MBe0D3G4ww+9vPQeLyTHbFtrW/QHtWHO05SgBj/Hr9s7DK/1sAeQSGz9KAAtD58W6NZXctD1QOcS9BaskXmzgMYPwGiRy+ClmG+aoIlYjKfSeiPShpM7w4N1tmD6cS7PHIq9MpuVv9vNQZP8DGHy02C5/eQPMA3qz5hBUQDdQtJ7x/muH5JMZ/Q1drg69xBpsjrM8Gw0fdbUrYcqq0bjoZF0J93QXoSZWn/1BmDJihrIp7DXaJXuLa3vs5ZnVgbkIf73jptiSLQeofCijGZEwjSOJ0hZ4hwH8P4DGTURNI4GbWqMvWjmYJ3XAC5lBWg/r4cVmvMYlx13SxMrLHMRg24ncWVAkY=
      file_glob: true
      file: build/libs/wasmtime-java-*-universal.jar
      cleanup: true
      on:
        tags: true
        repo: kawamuray/wasmtime-java
before_install:
- curl --fail -L https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh -o /tmp/install-jdk.sh
- . /tmp/install-jdk.sh -F 11
- rustup component add rustfmt
# https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
- cargo
- directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script: ./gradlew build copyJniLib
